import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { chemicalPalletItems } from "@/data/products";
import { getProductImage } from "@/data/productImages";

export const metadata: Metadata = {
  title: "Chemical Pallets Manufacturer | HDPE Spill Pallets | DYN Pallets",
  description: "DYN Pallets manufactures chemical pallets, HDPE spill containment pallets and chemical resistant plastic pallets for drums, IBCs, hazardous storage and industrial handling.",
  alternates: { canonical: "/products/chemical-pallets" },
};

export default function ChemicalPalletsPage() {
  const typeCards = [
    ["01", "HDPE Chemical Pallets", "HDPE chemical pallets provide a durable, waterproof and non-absorbent solution for chemical plants, warehouses, processing facilities and repeat-use logistics.", ["Chemical warehouses", "Drum handling", "Production areas", "Raw material storage"]],
    ["02", "Chemical Resistant Plastic Pallets", "Plastic chemical pallets suit environments exposed to industrial liquids, moisture and chemical substances. Compatibility should be checked for the exact chemical and conditions.", ["Acids and alkalis", "Solvents", "Corrosive areas", "Waterproof handling"]],
    ["03", "Heavy Duty Chemical Pallets", "Reinforced configurations support dense drums, large containers, industrial raw materials and repeated forklift handling.", ["Heavy chemical drums", "Bulk movement", "High-load storage", "Distribution operations"]],
    ["04", "Chemical Storage Pallets", "Structured support for drums, containers, raw materials and finished chemicals in warehouses, production areas and dedicated storage rooms.", ["Drum storage", "Finished goods", "Hazardous materials", "Industrial liquids"]],
    ["05", "Chemical Spill Pallets", "Containment platforms support drums and containers while providing a controlled area underneath for leaks and accidental spills.", ["Drum spill pallets", "HDPE spill pallets", "Oil spill pallets", "Custom containment"]],
    ["06", "Chemical Drum Pallets", "Stable support for single or multiple chemical drums, with integrated spill containment available where the application requires it.", ["Single drum", "2-drum", "4-drum", "Heavy-duty drum systems"]],
    ["07", "IBC Spill Containment Pallets", "Platforms for IBC containers with secondary containment matched to dimensions, loaded weight, liquid type and required sump capacity.", ["Single IBC", "Multi-IBC systems", "HDPE IBC pallets", "Custom IBC solutions"]],
    ["08", "Rackable Chemical Pallets", "Pallet configurations for compatible warehouse racking, selected around rack span, load distribution, dimensions and operating temperature.", ["Warehouse racking", "Rack span review", "Loaded storage", "Frequent handling"]],
    ["09", "4-Way Chemical Pallets", "Four-way forklift access improves flexibility during warehouse movement, truck loading, production handling and pallet positioning.", ["Forklift access", "Pallet jack", "Plant movement", "Logistics flow"]],
  ] as const;

  const requirementCards = [
    ["01", "Chemical or material", "Tell us what chemical, liquid or material will be stored or handled."], ["02", "Container type", "Specify drums, IBCs, totes, cans or another container format."], ["03", "Container dimensions", "Provide length, width, height or drum and IBC size."], ["04", "Total loaded weight", "Provide the complete loaded weight and how it is distributed."], ["05", "Pallet dimensions", "Send an existing pallet size or ask us to recommend a configuration."], ["06", "Quantity", "Tell us whether the requirement is one-time, project-based or recurring."], ["07", "Forklift entry", "Confirm whether 2-way or 4-way access is required."], ["08", "Storage method", "Identify floor storage, stacking or racking requirements."], ["09", "Operating environment", "Tell us whether use is indoor, outdoor, wet or chemical-exposed."], ["10", "Spill containment", "Provide container count, volume and required containment capacity."],
  ] as const;

  const applications = [
    ["01", "Chemical Manufacturing", "Plastic pallets for chemical industry operations involving raw materials, intermediate products, containers and finished chemicals."], ["02", "Chemical Warehousing", "Non-absorbent support for drums, packaged chemicals, containers and industrial materials."], ["03", "Hazardous Material Handling", "Appropriate pallet configurations for controlled movement and storage of hazardous material containers."], ["04", "Drum and IBC Storage", "Chemical drum pallets and IBC containment pallets for production and warehouse storage areas."], ["05", "Industrial Manufacturing", "Industrial chemical pallets for oils, lubricants and production materials used across manufacturing operations."], ["06", "Logistics and Distribution", "Durable chemical logistics pallets for movement between warehouses, plants and distribution operations."],
  ] as const;

  const faqs = [
    ["What are chemical pallets?", "Chemical pallets are industrial pallets designed for handling, storing or transporting chemicals, drums, IBCs and related materials. They may use chemical-resistant HDPE or other suitable plastics."], ["What material is used for chemical pallets?", "HDPE is commonly used because it provides durable, moisture-resistant and non-absorbent construction. Suitability must be checked against the specific chemical."], ["Are HDPE pallets chemical resistant?", "HDPE provides resistance to many industrial chemicals, but compatibility depends on chemical type, concentration, temperature and exposure period."], ["What is a chemical spill pallet?", "A chemical spill pallet supports drums or containers while providing a sump or containment area below them to capture leaks or spills."], ["Can chemical pallets be used with forklifts?", "Yes. Forklift chemical pallets can be supplied with suitable entry configurations, including 4-way access where required."], ["Do you provide rackable chemical pallets?", "Rackable requirements can be supported where the pallet design, load and racking system are compatible. Provide the rack span and required racking load."], ["Are chemical pallets reusable?", "Many plastic and HDPE chemical pallets are designed for repeat use. Service life depends on load, handling, chemical exposure and pallet condition."], ["Can DYN Pallets provide custom chemical pallets?", "Yes. Custom chemical pallets can be reviewed around dimensions, container size, load, handling equipment and operating environment."], ["What information is required for a quotation?", "Provide the chemical, container type and dimensions, total load, pallet size, quantity, entry, storage method, environment and containment requirement."], ["Why use plastic pallets for the chemical industry?", "Plastic pallets offer non-absorbent construction, moisture resistance, corrosion resistance and repeat-use capability for many industrial applications."],
  ] as const;

  return <div className="product-category-layout">
    <section className="page-hero texture-grid wooden-pallets-hero"><div className="page-hero-copy"><nav className="wooden-breadcrumbs" aria-label="Breadcrumb"><Link href="/products">Products</Link><span>/</span><span>Chemical Pallets</span></nav><h1>Chemical Pallets</h1><p className="wooden-hero-description">Chemical resistant pallets engineered for safe storage, handling, containment and transportation of chemicals, drums, IBCs and industrial materials.</p><div className="hero-actions wooden-hero-actions"><Link href="/contact" className="button button-primary">Request a Quote <ArrowUpRight size={18} /></Link><Link href="/contact" className="button button-ghost">Send Specification <ArrowUpRight size={17} /></Link></div></div><div className="wooden-hero-image"><Image src="/product-photos/chemical-pallets.webp" alt="Chemical pallets" fill priority className="wooden-pallet-product-image" /></div></section>

    <section className="wooden-page-section wooden-intro-section light-surface"><div className="wooden-content-shell"><div className="wooden-intro-layout"><span className="kicker">OVERVIEW</span><div className="wooden-content-flow wooden-intro-copy"><p>DYN Pallets manufactures and supplies chemical pallets for demanding chemical storage, manufacturing, warehouse, logistics and material handling applications.</p><p>From HDPE chemical pallets and chemical resistant plastic pallets to chemical spill pallets, drum containment systems and IBC spill containment pallets, solutions can be selected around the chemical, load, container, forklift movement and storage environment.</p><p>Chemical handling environments may require non-absorbent and corrosion-resistant materials that withstand acids, alkalis, solvents, oils, moisture and industrial liquids.</p><p>DYN Pallets provides industrial chemical pallets, chemical storage pallets and containment solutions for drums, containers, totes and IBCs.</p></div></div><div className="wooden-spec-strip-inner wooden-inline-specs"><div><span>Material</span><p className="wooden-spec-value">HDPE / Chemical-Resistant Plastic</p></div><div><span>Handling</span><p className="wooden-spec-value">Forklift / Pallet Jack / 4-Way Entry</p></div><div><span>Application</span><p className="wooden-spec-value">Storage / Handling / Spill Containment</p></div><div><span>Configuration</span><p className="wooden-spec-value">Standard / Heavy Duty / Rackable / Custom</p></div><div><span>Containers</span><p className="wooden-spec-value">Drums / Totes / IBCs / Packaged Chemicals</p></div></div></div></section>

    <section className="wooden-page-section light-surface"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">CHEMICAL PALLETS</span><h2>Industrial Chemical Pallets Built for Chemical Handling</h2></div><div className="wooden-content-flow"><p>A chemical pallet should do more than support a load. It should withstand the operating environment, provide stable support for containers, work with material handling equipment and help maintain controlled chemical storage and movement.</p><p>DYN Pallets supplies chemical resistant pallets where ordinary wooden or general-purpose pallet materials may not be appropriate.</p><p>Solutions can be developed for chemical drums, industrial containers, totes, IBCs, packaged chemicals, hazardous materials, oils, acids, alkalis, solvents, production chemicals and industrial liquids.</p><p>For regular chemical exposure, HDPE chemical pallets provide a durable, waterproof and non-absorbent alternative to many conventional pallet materials.</p></div></div></section>

    <section className="wooden-page-section wooden-page-section-alt"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">CHEMICAL PALLETS</span><h2>Types of Chemical Pallets</h2></div><div className="wooden-content-flow"><p>DYN Pallets supplies chemical pallet configurations for storage, manufacturing, material handling, logistics and spill management requirements.</p></div><div className="wooden-subsection-grid">{typeCards.map(([number, title, copy, items]) => <article className="wooden-subsection-card" key={title}><span className="wooden-card-index">{number}</span><h3>{title}</h3><div className="wooden-content-flow"><p>{copy}</p><p>Suitable for:</p><ul className="wooden-content-list">{items.map((item) => <li key={item}>{item}</li>)}</ul></div></article>)}</div></div></section>

    <section className="wooden-page-section light-surface"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">CHEMICAL PALLETS</span><h2>Specifications</h2></div><div className="wooden-content-flow"><p>Every chemical pallet specification should begin with the actual operating requirement.</p><div className="wooden-table-wrap"><table className="wooden-spec-table"><thead><tr><th>Specification</th><th>Available Options</th></tr></thead><tbody><tr><td>Material</td><td>HDPE / Chemical-resistant plastic</td></tr><tr><td>Entry</td><td>2-way / 4-way</td></tr><tr><td>Construction</td><td>Standard / Heavy duty / Rackable / Custom</td></tr><tr><td>Surface</td><td>Open deck / Closed deck depending on requirement</td></tr><tr><td>Load</td><td>Light / Medium / Heavy duty</td></tr><tr><td>Application</td><td>Storage / Handling / Shipping / Containment</td></tr><tr><td>Containers</td><td>Drums / Totes / IBCs / Packaged chemicals</td></tr><tr><td>Environment</td><td>Indoor / Outdoor / Wet / Chemical-exposed</td></tr><tr><td>Supply</td><td>Standard / Recurring / Custom requirement</td></tr></tbody></table></div><p>Final specifications depend on chemical compatibility, container dimensions, operating environment and load requirements.</p></div></div></section>

    <section className="wooden-page-section wooden-page-section-alt"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">CHEMICAL PALLETS</span><h2>Sizes & Configurations</h2></div><div className="wooden-content-flow"><p>Choosing the correct chemical pallet size affects load stability, container support, warehouse space utilisation, forklift handling and spill-control performance.</p><p>DYN Pallets can support standard and custom configurations for chemical handling requirements.</p></div><div className="wooden-subsection-grid is-two"><article className="wooden-subsection-card"><span className="wooden-card-index">01</span><h3>Standard Chemical Pallet Configurations</h3><div className="wooden-content-flow"><p>Common requirements include pallets for single or multiple drums, chemical totes, IBC containers, industrial containers and packaged chemicals.</p><p>The correct size should be selected around the container footprint rather than pallet dimensions alone.</p></div></article><article className="wooden-subsection-card"><span className="wooden-card-index">02</span><h3>Custom Chemical Pallets</h3><div className="wooden-content-flow"><p>Custom chemical pallets and custom spill containment pallets can be developed around product dimensions, drum arrangements, IBC dimensions, load weights, forklift requirements and storage systems.</p><p>Send the required dimensions, container type, loaded weight and handling details for quotation.</p></div></article></div></div></section>

    <section className="wooden-page-section light-surface"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">CHEMICAL PALLETS</span><h2>Built Around Your Chemical Handling Requirement</h2></div><div className="wooden-content-flow"><p>There is no single chemical pallet suitable for every industrial environment. Before recommending a pallet, DYN Pallets reviews compatibility, load, container type, handling, storage conditions and spill containment requirements.</p></div><div className="wooden-subsection-grid">{[["01","Chemical Compatibility","Provide the chemical type, concentration and expected exposure conditions. Compatibility should be confirmed for the specific application."],["02","Load","Provide static, dynamic and racking loads, container weight, liquid weight and load distribution."],["03","Container Type","Tell us whether the pallet supports drums, IBCs, totes, cans, chemical containers or packaged chemicals."],["04","Handling","Confirm forklift, pallet jack, warehouse truck, conveyor or internal material handling requirements."],["05","Storage Conditions","Identify indoor, outdoor, wet, production, processing or temperature-controlled storage conditions."],["06","Spill Containment","Provide container count, volume, chemical type, required containment capacity and available floor area."]] .map(([number,title,copy]) => <article className="wooden-subsection-card" key={title}><span className="wooden-card-index">{number}</span><h3>{title}</h3><div className="wooden-content-flow"><p>{copy}</p></div></article>)}</div></div></section>

    <section className="wooden-page-section wooden-page-section-alt"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">CHEMICAL PALLETS</span><h2>Applications</h2></div><div className="wooden-content-flow"><p>DYN Pallets supplies chemical handling pallets for a wide range of industrial applications.</p></div><div className="wooden-subsection-grid">{applications.map(([number,title,copy]) => <article className="wooden-subsection-card" key={title}><span className="wooden-card-index">{number}</span><h3>{title}</h3><div className="wooden-content-flow"><p>{copy}</p></div></article>)}</div></div></section>

    <section className="wooden-page-section light-surface"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">HDPE CHEMICAL PALLETS</span><h2>Why HDPE for Chemical Pallets?</h2></div><div className="wooden-content-flow"><p>HDPE is widely used for demanding industrial pallet applications because of its combination of durability, moisture resistance and non-absorbent construction. Compatibility should still be checked for the specific chemical and operating conditions.</p></div><div className="wooden-subsection-grid">{[["01","Chemical Resistance","Suitable HDPE formulations can provide resistance to many chemicals encountered in industrial environments."],["02","Corrosion Resistance","HDPE does not corrode like certain metal components in moisture-exposed and chemically demanding environments."],["03","Non-Absorbent Surface","Plastic surfaces do not soak up water and liquids in the same way as porous materials."],["04","Waterproof Construction","Plastic chemical pallets suit many wet or moisture-exposed environments without absorbing water into the pallet material."],["05","Reusable","Many HDPE pallets support repeated handling cycles where exposure, condition and operating requirements allow continued service."],["06","Easy to Maintain","Plastic surfaces are generally easier to wash and maintain where the chemical and cleaning process are compatible."]] .map(([number,title,copy]) => <article className="wooden-subsection-card" key={title}><span className="wooden-card-index">{number}</span><h3>{title}</h3><div className="wooden-content-flow"><p>{copy}</p></div></article>)}</div></div></section>

    <section className="wooden-page-section wooden-page-section-alt"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">SPILL CONTROL</span><h2>Spill Containment Pallets</h2></div><div className="wooden-content-flow"><p>Spill containment systems provide a controlled secondary containment area beneath drums, IBCs and containers.</p><p>DYN Pallets can support chemical, HDPE, plastic, drum, IBC, industrial, heavy-duty, oil and custom spill containment pallet requirements.</p><p>Selection should consider container capacity, number of containers, chemical compatibility, containment volume, floor space and handling method.</p></div></div></section>

    <section className="wooden-page-section light-surface"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">WHY DYN PALLETS</span><h2>Chemical Handling Focus</h2></div><div className="wooden-content-flow"><p>Chemical pallet selection should begin with the material being handled and the operating environment, not simply the nearest available pallet size.</p></div><div className="wooden-subsection-grid">{[["01","Chemical Industry Focus","Support for chemical manufacturing, warehousing, industrial processing and hazardous material handling."],["02","HDPE Options","Durable HDPE pallets for moisture, industrial liquids and chemical exposure requirements."],["03","Standard and Custom","Established pallet formats or custom solutions around containers, storage and operating conditions."],["04","Spill Containment","Drum spill pallets, chemical containment pallets and IBC spill containment solutions."],["05","Heavy Duty Capability","Reinforced configurations for demanding industrial loads and frequent warehouse movement."],["06","Recurring Supply","Ongoing supply support for chemical manufacturers, warehouses, logistics companies and industrial operations."]] .map(([number,title,copy]) => <article className="wooden-subsection-card" key={title}><span className="wooden-card-index">{number}</span><h3>{title}</h3><div className="wooden-content-flow"><p>{copy}</p></div></article>)}</div></div></section>

    <section className="wooden-page-section wooden-page-section-alt"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">REQUEST A QUOTE</span><h2>What We Need to Recommend the Right Chemical Pallet</h2></div><div className="wooden-content-flow"><p>Getting the correct quotation starts with the correct operating information. Send DYN Pallets the following details.</p></div><div className="wooden-requirement-grid">{requirementCards.map(([number,title,copy]) => <div className="wooden-requirement-card" key={title}><span>{number}</span><h3>{title}</h3><p>{copy}</p></div>)}</div><div className="wooden-content-flow"><p>Once these details are available, DYN Pallets can review the requirement and prepare an appropriate quotation.</p></div><div className="wooden-inline-cta"><Link href="/contact" className="button button-primary">Send Your Chemical Pallet Specification <ArrowUpRight size={17} /></Link></div></div></section>

    <section className="wooden-page-section light-surface"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">CHEMICAL PALLETS</span><h2>Related Chemical Pallet Solutions</h2></div><div className="wooden-content-flow"><p>DYN Pallets can support requirements beyond conventional plastic pallet platforms.</p></div><div className="wooden-subsection-grid">{[["01","HDPE Chemical Pallets","Chemical-resistant HDPE configurations for industrial handling, warehousing and repeat-use applications."],["02","Chemical Drum Pallets","Platforms designed around chemical drums and industrial container arrangements."],["03","Drum Spill Pallets","Containment systems for single or multiple drum storage areas."],["04","IBC Containment Pallets","Heavy-duty containment platforms designed around IBC storage requirements."],["05","Heavy Duty Chemical Pallets","Reinforced configurations for demanding industrial chemical loads."],["06","Custom Chemical Pallets","Custom platforms designed around unusual containers, equipment or storage requirements."]] .map(([number,title,copy]) => <article className="wooden-subsection-card" key={title}><span className="wooden-card-index">{number}</span><h3>{title}</h3><div className="wooden-content-flow"><p>{copy}</p></div></article>)}</div></div></section>

    <section className="section wooden-category-browser"><div className="section-heading split-heading"><div><span className="kicker">BROWSE CHEMICAL PALLET TYPES</span><h2>Explore the CP range.<br /><em>Specify with confidence.</em></h2></div><p>Review CP1 through CP9 chemical pallet formats by industrial application, handling requirement and pallet configuration.</p></div><div className="catalog-category-grid">{chemicalPalletItems.map((item, index) => <Link href={`/products/chemical-pallets/${item.slug}`} className="catalog-static-card" key={item.slug}><div className="catalog-static-image catalog-static-image-photo" style={{ backgroundImage: `url('${getProductImage(item.slug, "chemical-pallets")}')` }}><span>CP SERIES {String(index + 1).padStart(2, "0")}</span></div><div className="catalog-static-body"><span className="kicker">{String(index + 1).padStart(2, "0")} · {item.eyebrow}</span><h3>{item.name}</h3><p>{item.summary}</p><footer><span>View product</span><ArrowUpRight size={15} /></footer></div></Link>)}</div></section>

    <section className="wooden-page-section light-surface"><div className="wooden-content-shell"><div className="wooden-section-heading"><span className="kicker">CHEMICAL PALLETS</span><h2>Frequently Asked Questions</h2></div><div className="wooden-faq-list">{faqs.map(([question, answer], index) => <details key={question}><summary><span>{String(index + 1).padStart(2, "0")}</span>{question}<b>+</b></summary><p>{answer}</p></details>)}</div></div></section>

  </div>;
}
